# Basic configuration file
#---------------------------
# This configuration file is intended to be used as a basic example and test
# dataset for the KAPy suite. It is loosely based on the configuration used in the
# Ghana Climate Atlas, but with simplifications to make it run faster. Sample datasets
# can be downloaded from https://download.dmi.dk/Research_Projects/KAPy/
# For instructions, see 

configurationTables:
    inputs:  '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/config/inputs.tsv'
    indicators: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/config/indicators.tsv'
    scenarios:  '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/config/scenarios.tsv'
    periods:  '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/config/periods.tsv'
    seasons: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/config/seasons.tsv'
dirs:
    variables: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/results/1.variables/time_binning_periods/hadgem_rca'
    indicators: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/results/2.indicators/time_binning_periods/hadgem_rca'
    regridded: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/results/3.commmon_grid/time_binning_periods/hadgem_rca'
    ensstats: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/results/4.ensstats/time_binning_periods/hadgem_rca'
    arealstats: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/results/5.areal_statistics/time_binning_periods/hadgem_rca'
    plots: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/results/6.plots/hadgem_rca'
    netcdf: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/results/7.netcdf/hadgem_rca'

# Configuration options------------------------------------
arealstats:
    calcForMembers: True
cutouts:
    method: 'lonlatbox'
    xmin: 4.088
    xmax: 31.761
    ymin: 57.759
    ymax: 71.384
ensembles:
    upperPercentile: 90
    centralPercentile: 50
    lowerPercentile: 10
outputGrid:
    regriddingEngine: None