# Basic configuration file
#---------------------------
# This configuration file is intended to be used as a basic example and test
# dataset for the KAPy suite. It is loosely based on the configuration used in the
# Ghana Climate Atlas, but with simplifications to make it run faster. Sample datasets
# can be downloaded from https://download.dmi.dk/Research_Projects/KAPy/
# For instructions, see 

configurationTables:
    inputs:  '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/config/inputs.tsv'
    indicators: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/config/indicators.tsv'
    scenarios:  '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/config/scenarios.tsv'
    periods:  '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/config/periods.tsv'
    seasons: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/config/seasons.tsv'
dirs:
    variables: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/results/1.variables'
    indicators: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/results/2.indicators'
    regridded: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/results/3.commmon_grid'
    ensstats: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/results/4.ensstats'
    arealstats: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/results/5.areal_statistics'
    plots: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/results/6.plots'
    netcdf: '/lustre/storeC-ext/users/klimakverna/development/Klimakverna-pilot-KAPy/KAPy/results/7.netcdf'

# Configuration options------------------------------------
arealstats:
    calcForMembers: False
cutouts:
    method: 'lonlatbox'
    xmin: -4
    xmax: 2
    ymin: 4
    ymax: 12
ensembles:
    upperPercentile: 90
    centralPercentile: 50
    lowerPercentile: 10
outputGrid:
    regriddingEngine: 'cdo'
    cdoGriddes: './config/griddes.txt'